services:
  - type: web
    name: elimu-global-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm install -g postcss postcss-cli && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://instructors-elimu.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 116398057296-fvei9hl0h0ap1onm4nrq1eudum44b82o.apps.googleusercontent.com
    nodeVersion: 18.17.0
