version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instructors-elimu-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/instructors-elimu
      - JWT_SECRET=${JWT_SECRET:-default_secret}
      - SESSION_SECRET=${SESSION_SECRET:-default_session_secret}
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: instructors-elimu-mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=instructors-elimu
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
