services:
  - type: web
    name: elimu-global-backend
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          name: elimu-global-backend
          type: web
          property: port
      - key: MONGODB_URI
        fromService:
          name: instructors-elimu-db
          type: database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: instructors-elimu-db
    region: oregon
    plan: free
    databaseName: instructors-elimu
    ipAllowList: []
